TestOtc/WebApp/Models/Operations/BankModel.cs
using System;

namespace WebApp.Models.Operations
{
    public class BankModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }
}

TestOtc/WebApp/Models/Operations/InvoiceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models.Operations
{
    public class InvoiceModel
    {
        public Guid Id { get; set; }

        public string Number { get; set; }

        public Guid BankId { get; set; }

        public string InvoiceType { get; set; }

        public double Ammount { get; set; }
    }
}

TestOtc/WebApp/Models/Operations/TransferModel.cs
using System;

namespace WebApp.Models.Operations
{
    public class TransferModel
    {
        public Guid SenderInvoiceId { get; set; }

        public Guid RecipientInvoiceId { get; set; }

        public double Ammount { get; set; }
    }
}

TestOtc/WebApp/Controllers/AuthController.cs
using AuthService.Contracts;
using AuthService.Contracts.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebApp.Models.Auth;

namespace WebApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public ActionResult Login()
        {
            var model = new LoginModel();

            return View("login", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginModel loginModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Non Valid";
                return View("login", loginModel);
            }

            var authRequest = new AuthRequest()
            {
                Login = loginModel.Login,
                Password = loginModel.Password,
            };

            var authResult = await _authService.AuthAsync(authRequest);

            if (authResult.IsSuccess)
            {
                FormsAuthentication.SetAuthCookie(authResult.UserId.ToString(), true);
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("", "Пользователя с таким логином и паролем нет");
            return View("login", loginModel);
        }

        public ActionResult IsAuth()
        {
            var model = new IsAuthModel()
            {
                IsAuthen = HttpContext.User.Identity.IsAuthenticated,
            };

            return PartialView(model);
        }

        [Route("logout")]
        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            return View();
        }

        [Route("logout")]
        [HttpPost]
        [Authorize]
        public ActionResult PostLogout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

TestOtc/WebApp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TestOtc/WebApp/Controllers/OperationsController.cs
using AutoMapper;
using OperationsService.Contracts;
using OperationsService.Contracts.Dtos;
using OperationsService.Contracts.Exceptions;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApp.Models.Operations;

namespace WebApp.Controllers
{
    [Authorize]
    public class OperationsController : Controller
    {
        private readonly IOperationsService _operationsService;

        public OperationsController(IOperationsService operationsService)
        {
            _operationsService = operationsService;
        }

        [ActionName("SenderInvoices")]
        public async Task<ActionResult> GetSenderInvoicesAsync(Guid id)
        {
            var invoices = await _operationsService.GetSenderInvoicesAsync(id);

            var invoicesViewModel = Mapper.Map<IEnumerable<InvoiceModel>>(invoices);

            return PartialView(invoicesViewModel);
        }

        [ActionName("RecipientInvoices")]
        public async Task<ActionResult> GetRecipientInvoicesAsync(Guid id, Guid senderInvoiceId)
        {
            var invoices = await _operationsService.GetRecipientInvoicesAsync(id, senderInvoiceId);

            var invoicesViewModel = Mapper.Map<IEnumerable<InvoiceModel>>(invoices);

            return PartialView(invoicesViewModel);
        }

        [ActionName("banks")]
        public async Task<ActionResult> GetBankAsync()
        {
            var banks = await _operationsService.GetBanksAsync();

            var banksViewModel = Mapper.Map<IEnumerable<BankModel>>(banks);

            return PartialView(banksViewModel);
        }

        [HttpPost]
        [ActionName("Transfer")]
        public async Task<ActionResult> TransferAsync(TransferModel transferModel)
        {
            if (ModelState.IsValid)
            {
                var transferRequest = Mapper.Map<TransferRequest>(transferModel);

                if (Guid.TryParse(HttpContext.User.Identity.Name, out Guid userId))
                {
                    try
                    {
                        await _operationsService.TransferAsync(transferRequest, userId);
                    }
                    catch (TransferException ex)
                    {
                        return Json(new { success = false, m = string.Join(",", ex.Messages) });
                    }
                    catch (Exception ex)
                    {
                        return Json(new { success = false, m = ex.Message });
                    }

                    return Json(new { success = true });
                }
                else
                {
                    throw new UnauthorizedAccessException();
                }
            }
            else
            {
                return Json(new { success = false, m = "Ошибка ввода данных." });
            }
        }

        // GET: Operations
        public ActionResult Index()
        {
            return View();
        }
    }
}

TestOtc/WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestOtc/WebApp/Views/Operations/Banks.cshtml
@model IEnumerable<WebApp.Models.Operations.BankModel>

@foreach (var item in Model)
{
    <option id="@item.Id">
        @item.Name
    </option>
}

TestOtc/WebApp/Views/Operations/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row mt-4 mb-2 text-center">
    <div class="form-horizontal form-widgets col-md-12">
        <h2>Операции</h2>
    </div>
</div>
<div class="row">
    <div class="form-horizontal form-widgets col-md-12">

        <div class="form-group">
            Выберите банк
            <select class="combobox" id="sender-bank"></select>
        </div>

        <div class="form-group">
            <table class="table table-striped table-hover table-bordered" id="sender-invoices-table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Номер счета</th>
                        <th scope="col">Сумма</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody id="sender-invoices-tbody"></tbody>
            </table>
        </div>

    </div>

</div>

<div class="modal fade" id="transferModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="transferModalLabel">Перевод</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Transfer", "Operations", FormMethod.Post, htmlAttributes: new { id = "transfer_form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <input type="hidden" class="form-control" id="sender-invoice-id" name="senderInvoiceId">
                    </div>
                    <div class="form-group">
                        <label for="sender-invoice-number" class="col-form-label">Отправитель:</label>
                        <input type="text" class="form-control" id="sender-invoice-number" readonly>
                    </div>
                    <hr />
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Выберите банк получателя:</label>
                        <select class="combobox" id="recipient-bank"></select>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Выберите счет получателя:</label>
                        <table class="table table-striped table-hover table-bordered" id="recipient-invoices-table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Номер счета</th>
                                    <th scope="col">Сумма</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody id="recipient-invoices-tbody" data-toggle="buttons"></tbody>
                        </table>
                    </div>
                    <div class="form-group">
                        <label for="ammount" class="col-form-label">Сумма перевода:</label>
                        <input type="number" class="form-control" name="ammount" id="ammount" required>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="btn-transfer">Перевести</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            jQuery(function ($) {

                $("#transfer_form").on("submit", function (e) {
                    var postData = $(this).serializeArray();
                    var formURL = $(this).attr("action");
                    $.ajax({
                        url: formURL,
                        type: "POST",
                        data: postData,
                        success: function (data, textStatus, jqXHR) {
                            if (data.success) {
                                $('#transferModal').modal('toggle');
                                GetSenderInvoices();
                            }
                            else
                                alert(data.m);
                        },
                        error: function (jqXHR, status, error) {
                            alert(status + ": " + error);
                        }
                    });
                    e.preventDefault();
                });

                $("#btn-transfer").on('click', function () {
                    $("#transfer_form").submit();
                });

                $('#transferModal').on('show.bs.modal', function (event) {
                    var button = $(event.relatedTarget);
                    var modal = $(this);

                    var sender_invoice_id = button.data('sender-invoice-id');

                    modal.find('#sender-invoice-id').val(sender_invoice_id);
                    modal.find('#sender-invoice-number').val(button.data('sender-invoice-number'));
                    modal.find('#ammount').val('');

                    $("#recipient-bank").on('change', function () {
                        var id = $("#recipient-bank option:selected").attr('id');

                        if (id != null) {
                            $('#recipient-invoices-table').DataTable().destroy();

                            $("#recipient-invoices-tbody").load(`@Url.Action("RecipientInvoices", "Operations")/${id}?senderInvoiceId=${sender_invoice_id}`, function () {
                                $('#recipient-invoices-table').DataTable({
                                    aLengthMenu: [
                                        [5, 50, 100, 200, -1],
                                        [5, 50, 100, 200, "All"]
                                    ],
                                    iDisplayLength: 5,
                                    retrieve: true
                                });
                            });
                        }

                    }).load('@Url.Action("banks", "Operations")/', function () {
                        $("#recipient-bank").change();
                    });

                });

                $("#sender-bank").on('change', function () {
                    GetSenderInvoices();
                }).load('@Url.Action("banks", "Operations")/', function () {
                    $("#sender-bank").change()
                    });

                function GetSenderInvoices() {
                    var id = $("#sender-bank option:selected").attr('id');
                    if (id != null) {
                        $('#sender-invoices-table').DataTable().destroy();
                        $("#sender-invoices-tbody").load(`@Url.Action("SenderInvoices", "Operations")/${id}`, function () {
                            $('#sender-invoices-table').DataTable();
                        });
                    }
                }

            });
        });
    </script>

}

TestOtc/WebApp/Views/Operations/RecipientInvoices.cshtml
@model System.Collections.Generic.IEnumerable<WebApp.Models.Operations.InvoiceModel>

@foreach (var item in Model)
{
<tr>
    <td>
        @item.Number
    </td>
    <td>
        @item.Ammount
    </td>
    <td>
        <label class="btn btn-primary">
            <input type="radio" name="recipientInvoiceId" value="@item.Id" autocomplete="off" checked> Выбрать
        </label>
    </td>

</tr>
}

TestOtc/WebApp/Views/Operations/SenderInvoices.cshtml
@model System.Collections.Generic.IEnumerable<WebApp.Models.Operations.InvoiceModel>

@foreach (var item in Model)
{
<tr>
    <td>
        @item.Number
    </td>
    <td>
        @item.Ammount
    </td>
    <td>
        <button type="button" 
                class="btn btn-primary" 
                data-toggle="modal" 
                data-target="#transferModal" 
                data-sender-invoice-id="@item.Id"
                data-sender-invoice-number="@item.Number">Перевести</button>
    </td>

</tr>
}

TestOtc/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datatables")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            @Html.ActionLink("Test OTC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Операции", "Index", "Operations", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @{Html.RenderAction("IsAuth", "Auth"); }
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryunajax")
    @Scripts.Render("~/bundles/datatables")

    @RenderSection("scripts", required: false)
</body>
</html>